#!/bin/bash

echo -n "Sisesta oma nimi: "
read nimi
echo 
echo -n "Tere tulemast, $nimi"
echo
echo -n "Sisesta oma sünniaasta: "
read aasta

praegune_aasta=$(date +%Y)

vanus=$(( praegune_aasta - aasta ))
echo
echo -n "$nimi, sina oled $vanus aastat vana."
