#!/bin/bash

read -p "Sisesta ridade arv: " read_arv
read -p "Sisesta tärnide arv reas: " tarnid_arv

for (( i=1; i<=read_arv; i++ ))
do
  echo -n "$i.  "
  for (( j=1; j<=tarnid_arv; j++ ))
  do
    echo -n "* "
  done
  echo ""
done
