#!/bin/bash

# Kontroll funktsioon positiivse täisarvu jaoks
function on_positiivne_taisarv() {
  [[ "$1" =~ ^[1-9][0-9]*$ ]]
}

read -p "Sisesta ridade arv: " ridade_arv
if ! on_positiivne_taisarv "$ridade_arv"; then
  echo "Viga: palun sisesta positiivne täisarv ridade arvuks."
  exit 1
fi

for (( rida=1; rida<=ridade_arv; rida++ ))
do
  echo -n "$rida. "
  for (( t=1; t<=rida; t++ ))
  do
    echo -n "* "
  done
  echo ""
done
