#!/bin/bash
#Arvutab arvude paarisarvude summa, vahemik 1 kuni 10
summa=0
for (( arv=1; arv<11; arv++ ))
do
	jaak=$(( $arv % 2 ))
	if [ $jaak -eq 0 ]; then
		summa=$(( $summa + $arv ))
		echo $summa
	fi
done

echo "Arvude vahemikus 1 kuni 10 (k.a) paarisarvude summa on: $summa"
