#!/bin/bash

echo -n "Sisesta suvaline täisarv: "
read algarv

orig=$algarv
summa=0

while [ $algarv -ne 0 ]
do
    jaak=$(( algarv % 10 ))
    summa=$(( summa + jaak ))
    algarv=$(( algarv / 10 ))
done

echo "Arvu $orig numbrite summa on $summa"
